
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://danpan55.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Dani Wood"
title: "Dani Wood"
description: "Blog and Website of Dani Wood"
keywords: "dani, danielle, wood, Australian"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Hey! Thanks for stopping by..."
  - text: "What are you doing here?"

me-img: "/img/dani_profile.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "danpan55"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/arrows.jpg"
    date: "June 2015 - June 2016"
    description: "Moved into the eCommerce world to learn how to grow an online business."
  - image: "/img/timeline/fitness.jpg"
    date: "November 2013 - June 2015"
    description: "Fulfilled a life long dream to study fitness & personal training. Started my own fitness business."
  - image: "/img/timeline/gazella.jpg"
    date: "December 2012"
    description: "Started exploring the tech world and started my first online business, RunGazella.com."
  - image: "/img/timeline/banking.jpg"
    date: "Febuary 2006 - December 2012"
    description: "Worked in banking in Sydney and London, on commodities and funding projects related to the GFC."
  - image: "/img/timeline/graduate.png"
    date: "December 2005"
    description: "Graduated from the Bachelor of Accounting Co-op Scholarship Program from UTS."

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "dani.wood321@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Dani Wood is an awesome person. She lives in Denver, Colorado where she likes spending time in the mountains and drinking coffee."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/danielle-wood"
  - title: "twitter"
    url: "https://twitter.com/danpan55"
  - title: "github"
    url: "https://github.com/danpan55"
  - title: "instagram"
    url: "https://www.instagram.com/daniofthewoods/"

############
# 404 page #
############

404-img: "/img/dani404.png"


################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Skills: 'skills'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
